"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/landingpage/Header";
import Footer from "@/components/landingpage/Footer";
import { usePathname } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";
import { EdgeStoreProvider } from '../lib/edgestore';

const inter = Inter({ subsets: ["latin"] }); 

//  const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const showNavbar = pathname === '/';

  return (
    <html lang="en">
      <body className={inter.className}>
      {showNavbar &&   <Header/>}
      <Toaster/>
      <EdgeStoreProvider>{children}</EdgeStoreProvider>
        {showNavbar && <Footer/>}
        </body>
    </html>
  );
}
